kind: Deployment
apiVersion: apps/v1
metadata:
  name: versionminimum
  labels:
    app: versionminimum
spec:
  selector:
    matchLabels:
      app: versionminimum
  template:
    metadata:
      labels:
        app: versionminimum
    spec:
      containers:
        - name: versionminimum
          image: nodejs-httpserver:versionminimum
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: versionminimum
spec:
  selector:
    app: versionminimum
  ports:
    - protocol: TCP
      port: 8080 