apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-versionminimum
  namespace: nodejs-httpserver
spec:
  workload:
    kind: Deployment
    name: versionminimum
    namespace: nodejs-httpserver
