apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-httpserver
  namespace: golang-httpserver
spec:
  workload:
    kind: Deployment
    name: httpserver
    namespace: golang-httpserver
