kind: Deployment
apiVersion: apps/v1
metadata:
  name: envmanifest
  labels:
    app: envmanifest
spec:
  selector:
    matchLabels:
      app: envmanifest
  template:
    metadata:
      labels:
        app: envmanifest
    spec:
      containers:
        - name: envmanifest
          image: ghcr.io/odigos-io/synthetic-apps/nodejs-httpserver:envmanifest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: NODE_OPTIONS
              value: "--require /app/execute_before.js --max-old-space-size=256"
---
kind: Service
apiVersion: v1
metadata:
  name: envmanifest
spec:
  selector:
    app: envmanifest
  ports:
    - protocol: TCP
      port: 8080 