apiVersion: odigos.io/v1alpha1
kind: Action
metadata:
  name: url-templatization-default
  namespace: odigos-system
spec:
  actionName: url-templatization-default
  notes: >-
    Default URL templatization enabled for Deployment url-templatization in
    nodejs-url-templatization (nodejs/javascript synthetic app).
  signals:
    - TRACES
  urlTemplatization:
    default:
      - disabled: false
    rules:
      - scopes:
          sources:
            - kind: Deployment
              name: url-templatization
              namespace: nodejs-url-templatization
          languages:
            - javascript
        templates:
          - '/plain-http/default/method/custom-rule/items/{item-id}'