apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-live-ready-fail
  namespace: nodejs-k8s-health
spec:
  workload:
    kind: Deployment
    name: live-ready-fail
    namespace: nodejs-k8s-health
