apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-versionunsupported
  namespace: python-httpserver
spec:
  workload:
    kind: Deployment
    name: versionunsupported
    namespace: python-httpserver
