kind: Deployment
apiVersion: apps/v1
metadata:
  name: tail-sampling-duration
  labels:
    app: tail-sampling-duration
spec:
  selector:
    matchLabels:
      app: tail-sampling-duration
  template:
    metadata:
      labels:
        app: tail-sampling-duration
    spec:
      containers:
        - name: tail-sampling-duration
          image: ghcr.io/odigos-io/synthetic-apps/nodejs-tail-sampling:tail-sampling
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: tail-sampling-duration
spec:
  selector:
    app: tail-sampling-duration
  ports:
    - protocol: TCP
      port: 8080
