apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-nodejs-tail-sampling-ns
  namespace: nodejs-tail-sampling
spec:
  workload:
    kind: Namespace
    name: nodejs-tail-sampling
    namespace: nodejs-tail-sampling
