apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-httppayload
  namespace: nodejs-httppayload
spec:
  workload:
    kind: Deployment
    name: httppayload
    namespace: nodejs-httppayload
