apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-crash-exit
  namespace: nodejs-k8s-health
spec:
  workload:
    kind: Deployment
    name: crash-exit
    namespace: nodejs-k8s-health
