#!/usr/bin/env bash
# Generate a Helm values override that points enterprise Odigos components at
# Depot registry images from odigos-enterprise CI (build.yaml).
#
# Currently overrides only enterprise-registry components (instrumentor, ui).
# Odiglet/agents and OSS images still come from the chart defaults.
#
# Tag format matches Depot save-tag:
#   <GITHUB_REPOSITORY_NAME>-<component>-<GITHUB_RUN_ID>
# e.g. odigos-enterprise-instrumentor-1658821493
#
# Usage:
#   ./generate-odigos-ci-images-values.sh <GITHUB_RUN_ID> [output-file]
set -euo pipefail

GITHUB_RUN_ID="${1:?GITHUB_RUN_ID is required (enterprise CI workflow run id)}"
OUT="${2:-odigos-ci-images.values.yaml}"

GITHUB_REPOSITORY_NAME="${GITHUB_REPOSITORY_NAME:-odigos-enterprise}"
DEPOT_ORG_ID="${DEPOT_ORG_ID:-p0xd21zf5r}"
DEPOT_ODIGOS_ENTERPRISE_REGISTRY_ID="${DEPOT_ODIGOS_ENTERPRISE_REGISTRY_ID:-w8zkfqwtt3}"
DEPOT_PULL_SECRET_NAME="${DEPOT_PULL_SECRET_NAME:-depot-regcred}"

depot_image() {
  local project="$1"
  local component="$2"
  printf '%s.registry.depot.dev/%s:%s-%s-%s' \
    "${DEPOT_ORG_ID}" \
    "${project}" \
    "${GITHUB_REPOSITORY_NAME}" \
    "${component}" \
    "${GITHUB_RUN_ID}"
}

instrumentor_img="$(depot_image "${DEPOT_ODIGOS_ENTERPRISE_REGISTRY_ID}" instrumentor)"
ui_img="$(depot_image "${DEPOT_ODIGOS_ENTERPRISE_REGISTRY_ID}" ui)"

cat >"${OUT}" <<EOF
# Generated by generate-odigos-ci-images-values.sh — do not edit.
# Source: odigos-enterprise CI Depot images for run ${GITHUB_RUN_ID}
# Enterprise registry project only (${DEPOT_ODIGOS_ENTERPRISE_REGISTRY_ID}).

imagePullSecrets:
  - ${DEPOT_PULL_SECRET_NAME}

images:
  enterprise-instrumentor: ${instrumentor_img}
  enterprise-ui: ${ui_img}
EOF

echo "Wrote ${OUT}"
