#!/usr/bin/env bash
# Generate a Helm values override that points Odigos cluster components at
# Depot registry images from odigos-enterprise CI (build.yaml).
#
# Registries (from enterprise CI env):
#   enterprise → instrumentor, ui
#   odiglet    → odiglet, agents
#   oss        → autoscaler, scheduler, collector
#
# Tag format matches Depot save-tag:
#   <GITHUB_REPOSITORY_NAME>-<component>-<GITHUB_RUN_ID>
# e.g. odigos-enterprise-instrumentor-1658821493
#
# Usage:
#   ./generate-odigos-ci-images-values.sh <GITHUB_RUN_ID> [output-file]
set -euo pipefail

GITHUB_RUN_ID="${1:?GITHUB_RUN_ID is required (enterprise CI workflow run id)}"
OUT="${2:-odigos-ci-images.values.yaml}"

GITHUB_REPOSITORY_NAME="${GITHUB_REPOSITORY_NAME:-odigos-enterprise}"
DEPOT_ORG_ID="${DEPOT_ORG_ID:-p0xd21zf5r}"
DEPOT_ODIGOS_ENTERPRISE_REGISTRY_ID="${DEPOT_ODIGOS_ENTERPRISE_REGISTRY_ID:-w8zkfqwtt3}"
DEPOT_ODIGLET_ENTERPRISE_REGISTRY_ID="${DEPOT_ODIGLET_ENTERPRISE_REGISTRY_ID:-1wj57h6qh9}"
DEPOT_ODIGOS_OSS_REGISTRY_ID="${DEPOT_ODIGOS_OSS_REGISTRY_ID:-570xmd9kld}"
DEPOT_PULL_SECRET_NAME="${DEPOT_PULL_SECRET_NAME:-depot-regcred}"
INCLUDE_IMAGE_PULL_SECRETS="${INCLUDE_IMAGE_PULL_SECRETS:-true}"

depot_image() {
  local project="$1"
  local component="$2"
  printf '%s.registry.depot.dev/%s:%s-%s-%s' \
    "${DEPOT_ORG_ID}" \
    "${project}" \
    "${GITHUB_REPOSITORY_NAME}" \
    "${component}" \
    "${GITHUB_RUN_ID}"
}

instrumentor_img="$(depot_image "${DEPOT_ODIGOS_ENTERPRISE_REGISTRY_ID}" instrumentor)"
ui_img="$(depot_image "${DEPOT_ODIGOS_ENTERPRISE_REGISTRY_ID}" ui)"
odiglet_img="$(depot_image "${DEPOT_ODIGLET_ENTERPRISE_REGISTRY_ID}" odiglet)"
agents_img="$(depot_image "${DEPOT_ODIGLET_ENTERPRISE_REGISTRY_ID}" agents)"
autoscaler_img="$(depot_image "${DEPOT_ODIGOS_OSS_REGISTRY_ID}" autoscaler)"
scheduler_img="$(depot_image "${DEPOT_ODIGOS_OSS_REGISTRY_ID}" scheduler)"
collector_img="$(depot_image "${DEPOT_ODIGOS_OSS_REGISTRY_ID}" collector)"

{
  cat <<EOF
# Generated by generate-odigos-ci-images-values.sh — do not edit.
# Source: odigos-enterprise CI Depot images for run ${GITHUB_RUN_ID}

EOF
  if [[ "${INCLUDE_IMAGE_PULL_SECRETS}" == "true" ]]; then
    cat <<EOF
imagePullSecrets:
  - ${DEPOT_PULL_SECRET_NAME}

EOF
  fi
  cat <<EOF
images:
  # Enterprise → ${DEPOT_ODIGOS_ENTERPRISE_REGISTRY_ID}
  enterprise-instrumentor: ${instrumentor_img}
  enterprise-ui: ${ui_img}
  # Odiglet / agents → ${DEPOT_ODIGLET_ENTERPRISE_REGISTRY_ID}
  enterprise-odiglet: ${odiglet_img}
  enterprise-agents: ${agents_img}
  # OSS (built in enterprise CI) → ${DEPOT_ODIGOS_OSS_REGISTRY_ID}
  autoscaler: ${autoscaler_img}
  scheduler: ${scheduler_img}
  collector: ${collector_img}
EOF
} >"${OUT}"

echo "Wrote ${OUT}"
