apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-versionlatest
  namespace: python-httpserver
spec:
  workload:
    kind: Deployment
    name: versionlatest
    namespace: python-httpserver
