kind: Deployment
apiVersion: apps/v1
metadata:
  name: versionlatest
  labels:
    app: versionlatest
spec:
  selector:
    matchLabels:
      app: versionlatest
  template:
    metadata:
      labels:
        app: versionlatest
    spec:
      containers:
        - name: versionlatest
          image: nodejs-httpserver:versionlatest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: versionlatest
spec:
  selector:
    app: versionlatest
  ports:
    - protocol: TCP
      port: 8080
