apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-head-sampling
  namespace: python-head-sampling
spec:
  workload:
    kind: Deployment
    name: head-sampling
    namespace: python-head-sampling
