kind: Deployment
apiVersion: apps/v1
metadata:
  name: envdockerfile
  labels:
    app: envdockerfile
spec:
  selector:
    matchLabels:
      app: envdockerfile
  template:
    metadata:
      labels:
        app: envdockerfile
    spec:
      containers:
        - name: envdockerfile
          image: ghcr.io/odigos-io/synthetic-apps/java-httpserver:envdockerfile
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
kind: Service
apiVersion: v1
metadata:
  name: envdockerfile
spec:
  selector:
    app: envdockerfile
  ports:
    - protocol: TCP
      port: 8080 