# Periodic outbound timer; first span is always HTTP client to head-sampling-http-server.
kind: Deployment
apiVersion: apps/v1
metadata:
  name: head-sampling-http-client
  labels:
    app: head-sampling-http-client
spec:
  selector:
    matchLabels:
      app: head-sampling-http-client
  template:
    metadata:
      labels:
        app: head-sampling-http-client
    spec:
      containers:
        - name: head-sampling-http-client
          image: ghcr.io/odigos-io/synthetic-apps/nodejs-head-sampling:head-sampling
          imagePullPolicy: IfNotPresent
          env:
            - name: HTTP_MATCH_ENABLE_ROUTES
              value: "false"
            - name: HTTP_MATCH_PERIODIC_OUTBOUND
              value: "true"
            - name: HTTP_MATCH_PEER_BASE_URL
              value: "http://head-sampling-http-server:8080"
            - name: HTTP_MATCH_EXACT_PEER_BASE_URL
              value: "http://head-sampling-http-server:8080"
            - name: HTTP_MATCH_OUTBOUND_INTERVAL_MS
              value: "10000"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
