apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-url-templatization-multi-rules
  namespace: nodejs-url-templatization
spec:
  workload:
    kind: Deployment
    name: url-templatization-multi-rules
    namespace: nodejs-url-templatization
