apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-tail-sampling-errors
  namespace: python-tail-sampling
spec:
  workload:
    kind: Deployment
    name: tail-sampling-errors
    namespace: python-tail-sampling
