quarkus.http.port=8080
quarkus.mongodb.connection-string=${MONGO_URI:mongodb://mongodb:27017}
quarkus.mongodb.database=stacks
mp.messaging.incoming.catalog-events.connector=smallrye-rabbitmq
mp.messaging.incoming.catalog-events.host=${RABBITMQ_HOST:rabbitmq}
mp.messaging.incoming.catalog-events.port=5672
mp.messaging.incoming.catalog-events.username=guest
mp.messaging.incoming.catalog-events.password=guest
mp.messaging.incoming.catalog-events.queue=catalog-events
