apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-versionminimum
  namespace: golang-httpserver
spec:
  workload:
    kind: Deployment
    name: versionminimum
    namespace: golang-httpserver
