apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-starts-after-instrumentation
  namespace: nodejs-agent-stability
spec:
  workload:
    kind: Deployment
    name: starts-after-instrumentation
    namespace: nodejs-agent-stability
