kind: Deployment
apiVersion: apps/v1
metadata:
  name: envdockerfile
  labels:
    app: envdockerfile
spec:
  selector:
    matchLabels:
      app: envdockerfile
  template:
    metadata:
      labels:
        app: envdockerfile
    spec:
      containers:
        - name: envdockerfile
          image: nodejs-httpserver:envdockerfile
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: envdockerfile
spec:
  selector:
    app: envdockerfile
  ports:
    - protocol: TCP
      port: 8080 