apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-versionveryold
  namespace: python-httpserver
spec:
  workload:
    kind: Deployment
    name: versionveryold
    namespace: python-httpserver
