apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-workload-types-daemonset
  namespace: nodejs-workload-types
spec:
  workload:
    kind: DaemonSet
    name: workload-types-daemonset
    namespace: nodejs-workload-types
