apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-workload-types-cronjob
  namespace: nodejs-workload-types
spec:
  workload:
    kind: CronJob
    name: workload-types-cronjob
    namespace: nodejs-workload-types
