apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-kubelet-health-probes
  namespace: python-head-sampling
spec:
  workload:
    kind: Deployment
    name: kubelet-health-probes
    namespace: python-head-sampling
