apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-tail-sampling
  namespace: python-tail-sampling
spec:
  workload:
    kind: Deployment
    name: tail-sampling
    namespace: python-tail-sampling
