apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-workload-types-deployment
  namespace: nodejs-workload-types
spec:
  workload:
    kind: Deployment
    name: workload-types-deployment
    namespace: nodejs-workload-types
