apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-invalid-image
  namespace: nodejs-k8s-health
spec:
  workload:
    kind: Deployment
    name: invalid-image
    namespace: nodejs-k8s-health
