kind: Deployment
apiVersion: apps/v1
metadata:
  name: versionveryold
  labels:
    app: versionveryold
spec:
  selector:
    matchLabels:
      app: versionveryold
  template:
    metadata:
      labels:
        app: versionveryold
    spec:
      containers:
        - name: versionveryold
          image: ghcr.io/odigos-io/synthetic-apps/nodejs-httpserver:versionveryold
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
kind: Service
apiVersion: v1
metadata:
  name: versionveryold
spec:
  selector:
    app: versionveryold
  ports:
    - protocol: TCP
      port: 8080 