kind: Deployment
apiVersion: apps/v1
metadata:
  name: httpserver
  labels:
    app: httpserver
spec:
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
        - name: httpserver
          image: ghcr.io/odigos-io/synthetic-apps/nodejs-httpserver:httpserver
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: httpserver
spec:
  selector:
    app: httpserver
  ports:
    - protocol: TCP
      port: 8080 