apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: instrument-httpserver
  namespace: nodejs-httpserver
spec:
  workload:
    kind: Deployment
    name: httpserver
    namespace: nodejs-httpserver
