name: Build Depot Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'nodejs/grpc/**'
      - 'scenarios/head-sampling-http/**'
      - 'scenarios/tail-sampling/**'
      - 'scenarios/url-templatization/**'
      - '.github/workflows/build-depot-images.yml'

permissions:
  contents: read
  id-token: write

env:
  DEPOT_REGISTRY: 'p0xd21zf5r.registry.depot.dev'

jobs:
  build-and-push:
    runs-on: depot-ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: depot/setup-action@v1
      - name: Login to Depot Registry
        run: docker login --username x-token --password ${{ secrets.DEPOT_SYNTHTIC_APPS_PUSH_TOKEN }} ${DEPOT_REGISTRY}

      - name: Build and push nodejs-head-sampling-http
        uses: depot/build-push-action@v1
        with:
          project: ddgftn5pcl
          push: true
          platforms: linux/amd64,linux/arm64
          file: scenarios/head-sampling-http/nodejs/deployments/head-sampling/Dockerfile
          context: scenarios/head-sampling-http/nodejs
          tags: ${{ env.DEPOT_REGISTRY }}/synthetic-apps:nodejs-head-sampling-http

      - name: Build and push python-head-sampling-http
        uses: depot/build-push-action@v1
        with:
          project: ddgftn5pcl
          push: true
          platforms: linux/amd64,linux/arm64
          file: scenarios/head-sampling-http/python/deployments/head-sampling/Dockerfile
          context: scenarios/head-sampling-http/python
          tags: ${{ env.DEPOT_REGISTRY }}/synthetic-apps:python-head-sampling-http

      - name: Build and push java-head-sampling-http
        uses: depot/build-push-action@v1
        with:
          project: ddgftn5pcl
          push: true
          platforms: linux/amd64,linux/arm64
          file: scenarios/head-sampling-http/java/deployments/head-sampling/Dockerfile
          context: scenarios/head-sampling-http/java
          tags: ${{ env.DEPOT_REGISTRY }}/synthetic-apps:java-head-sampling-http

      - name: Build and push nodejs-grpc
        uses: depot/build-push-action@v1
        with:
          project: ddgftn5pcl
          push: true
          platforms: linux/amd64,linux/arm64
          file: nodejs/grpc/deployments/grpc/Dockerfile
          context: nodejs/grpc
          tags: ${{ env.DEPOT_REGISTRY }}/synthetic-apps:nodejs-grpc

      - name: Build and push nodejs-tail-sampling
        uses: depot/build-push-action@v1
        with:
          project: ddgftn5pcl
          push: true
          platforms: linux/amd64,linux/arm64
          file: scenarios/tail-sampling/nodejs/deployments/tail-sampling/Dockerfile
          context: scenarios/tail-sampling/nodejs
          tags: ${{ env.DEPOT_REGISTRY }}/synthetic-apps:nodejs-tail-sampling

      - name: Build and push python-tail-sampling
        uses: depot/build-push-action@v1
        with:
          project: ddgftn5pcl
          push: true
          platforms: linux/amd64,linux/arm64
          file: scenarios/tail-sampling/python/deployments/tail-sampling/Dockerfile
          context: scenarios/tail-sampling/python
          tags: ${{ env.DEPOT_REGISTRY }}/synthetic-apps:python-tail-sampling

      - name: Build and push java-tail-sampling
        uses: depot/build-push-action@v1
        with:
          project: ddgftn5pcl
          push: true
          platforms: linux/amd64,linux/arm64
          file: scenarios/tail-sampling/java/deployments/tail-sampling/Dockerfile
          context: scenarios/tail-sampling/java
          tags: ${{ env.DEPOT_REGISTRY }}/synthetic-apps:java-tail-sampling

      - name: Build and push nodejs-url-templatization
        uses: depot/build-push-action@v1
        with:
          project: ddgftn5pcl
          push: true
          platforms: linux/amd64,linux/arm64
          file: scenarios/url-templatization/nodejs/deployments/url-templatization/Dockerfile
          context: scenarios/url-templatization/nodejs
          tags: ${{ env.DEPOT_REGISTRY }}/synthetic-apps:nodejs-url-templatization
