name: Build Depot Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'nodejs/grpc/**'
      - 'scenarios/head-sampling-http/**'
      - 'scenarios/tail-sampling/**'
      - 'scenarios/runtime-versions/**'
      - '.github/workflows/build-depot-images.yml'

permissions:
  contents: read
  id-token: write

env:
  DEPOT_REGISTRY: 'p0xd21zf5r.registry.depot.dev'

jobs:
  build-and-push:
    runs-on: depot-ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: depot/setup-action@v1
      - name: Login to Depot Registry
        run: docker login --username x-token --password ${{ secrets.DEPOT_SYNTHTIC_APPS_PUSH_TOKEN }} ${DEPOT_REGISTRY}

      - name: Build and push nodejs-head-sampling-http
        uses: depot/build-push-action@v1
        with:
          project: ddgftn5pcl
          push: true
          platforms: linux/amd64,linux/arm64
          file: scenarios/head-sampling-http/nodejs/deployments/head-sampling/Dockerfile
          context: scenarios/head-sampling-http/nodejs
          tags: ${{ env.DEPOT_REGISTRY }}/synthetic-apps:nodejs-head-sampling-http

      - name: Build and push python-head-sampling-http
        uses: depot/build-push-action@v1
        with:
          project: ddgftn5pcl
          push: true
          platforms: linux/amd64,linux/arm64
          file: scenarios/head-sampling-http/python/deployments/head-sampling/Dockerfile
          context: scenarios/head-sampling-http/python
          tags: ${{ env.DEPOT_REGISTRY }}/synthetic-apps:python-head-sampling-http

      - name: Build and push java-head-sampling-http
        uses: depot/build-push-action@v1
        with:
          project: ddgftn5pcl
          push: true
          platforms: linux/amd64,linux/arm64
          file: scenarios/head-sampling-http/java/deployments/head-sampling/Dockerfile
          context: scenarios/head-sampling-http/java
          tags: ${{ env.DEPOT_REGISTRY }}/synthetic-apps:java-head-sampling-http

      - name: Build and push nodejs-grpc
        uses: depot/build-push-action@v1
        with:
          project: ddgftn5pcl
          push: true
          platforms: linux/amd64,linux/arm64
          file: nodejs/grpc/deployments/grpc/Dockerfile
          context: nodejs/grpc
          tags: ${{ env.DEPOT_REGISTRY }}/synthetic-apps:nodejs-grpc

      - name: Build and push nodejs-tail-sampling
        uses: depot/build-push-action@v1
        with:
          project: ddgftn5pcl
          push: true
          platforms: linux/amd64,linux/arm64
          file: scenarios/tail-sampling/nodejs/deployments/tail-sampling/Dockerfile
          context: scenarios/tail-sampling/nodejs
          tags: ${{ env.DEPOT_REGISTRY }}/synthetic-apps:nodejs-tail-sampling

      - name: Build and push python-tail-sampling
        uses: depot/build-push-action@v1
        with:
          project: ddgftn5pcl
          push: true
          platforms: linux/amd64,linux/arm64
          file: scenarios/tail-sampling/python/deployments/tail-sampling/Dockerfile
          context: scenarios/tail-sampling/python
          tags: ${{ env.DEPOT_REGISTRY }}/synthetic-apps:python-tail-sampling

      - name: Build and push java-tail-sampling
        uses: depot/build-push-action@v1
        with:
          project: ddgftn5pcl
          push: true
          platforms: linux/amd64,linux/arm64
          file: scenarios/tail-sampling/java/deployments/tail-sampling/Dockerfile
          context: scenarios/tail-sampling/java
          tags: ${{ env.DEPOT_REGISTRY }}/synthetic-apps:java-tail-sampling

  build-runtime-versions:
    runs-on: depot-ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # - lang: nodejs
          #   variant: versionlatest
          # - lang: nodejs
          #   variant: versionminimum
          # - lang: nodejs
          #   variant: versionunsupported
          # - lang: nodejs
          #   variant: versionveryold
          - lang: python
            variant: versionlatest
          - lang: python
            variant: versionminimum
          - lang: python
            variant: versionminimumlegacy
          - lang: python
            variant: versionunsupported
          - lang: python
            variant: versionveryold
          # - lang: java
          #   variant: versionlatest
          # - lang: java
          #   variant: versionminimum
          # - lang: java
          #   variant: versionunsupported
          # - lang: java
          #   variant: versionveryold
          # - lang: golang
          #   variant: versionlatest
          # - lang: golang
          #   variant: versionminimum
          # - lang: golang
          #   variant: versionunsupported
          # - lang: golang
          #   variant: versionveryold
    steps:
      - uses: actions/checkout@v7

      - uses: depot/setup-action@v1
      - name: Login to Depot Registry
        run: docker login --username x-token --password ${{ secrets.DEPOT_SYNTHTIC_APPS_PUSH_TOKEN }} ${DEPOT_REGISTRY}

      - name: Build and push ${{ matrix.lang }}-runtime-versions-${{ matrix.variant }}
        uses: depot/build-push-action@v1
        with:
          project: ddgftn5pcl
          push: true
          platforms: linux/amd64,linux/arm64
          file: scenarios/runtime-versions/${{ matrix.lang }}/deployments/${{ matrix.variant }}/Dockerfile
          context: scenarios/runtime-versions/${{ matrix.lang }}
          tags: ${{ env.DEPOT_REGISTRY }}/synthetic-apps:${{ matrix.lang }}-runtime-versions-${{ matrix.variant }}
