name: Build Depot Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'nodejs/head-sampling/**'
      - '.github/workflows/build-depot-images.yml'

permissions:
  contents: read
  id-token: write

env:
  DEPOT_REGISTRY: 'p0xd21zf5r.registry.depot.dev'

jobs:
  build-and-push:
    runs-on: depot-ubuntu-24.04-2
    steps:
      - uses: actions/checkout@v7
      
      - uses: depot/setup-action@v1
      - name: Login to Depot Registry
        run: docker login --username x-token --password ${{ secrets.DEPOT_PUSH_TOKEN }} ${DEPOT_REGISTRY}

      - name: Build and push nodejs-head-sampling-http
        uses: depot/build-push-action@v1
        with:
          project: ddgftn5pcl
          push: true
          platforms: linux/amd64,linux/arm64
          file: nodejs/head-sampling/deployments/head-sampling/Dockerfile
          context: nodejs/head-sampling
          tags: ${{ env.DEPOT_REGISTRY }}/nodejs-head-sampling-http:latest
