name: Odigos Scenario E2E

on:
  workflow_dispatch:
    inputs:
      odigos_version:
        description: 'Odigos version to install (e.g. v1.29.2 or 1.30.0-pre2 or 1.31.0-rc1)'
        required: true
        type: string
      scenario:
        description: 'Scenario to test'
        required: true
        type: choice
        options:
          - tail-sampling
          - head-sampling-http
          - head-sampling-grpc
          - url-templatization
      languages:
        description: 'Comma-separated languages (nodejs, python, java)'
        required: true
        type: string
        default: nodejs
      tier:
        description: 'Odigos tier to install'
        required: true
        type: choice
        options:
          - enterprise
          - oss
        default: enterprise

env:
  DEPOT_REGISTRY: p0xd21zf5r.registry.depot.dev

jobs:
  scenario-e2e:
    runs-on: depot-ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: ./.github/actions/odigos-scenario-e2e
        with:
          odigos_version: ${{ inputs.odigos_version }}
          scenario: ${{ inputs.scenario }}
          languages: ${{ inputs.languages }}
          tier: ${{ inputs.tier }}
        env:
          ODIGOS_TOKEN_SYNTHTIC_APPS_TESTS_CI: ${{ secrets.ODIGOS_TOKEN_SYNTHTIC_APPS_TESTS_CI }}
          DEPOT_SYNTHTIC_APPS_PULL_TOKEN: ${{ secrets.DEPOT_SYNTHTIC_APPS_PULL_TOKEN }}
