name: Odigos Scenario E2E (All)

on:
  workflow_dispatch:
    inputs:
      odigos_version:
        description: 'Odigos version to install (e.g. v1.29.2 or 1.30.0-pre2 or 1.31.0-rc1)'
        required: true
        type: string

env:
  DEPOT_REGISTRY: p0xd21zf5r.registry.depot.dev

jobs:
  scenario-e2e:
    runs-on: depot-ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - scenario: tail-sampling
            tier: oss
            language: nodejs
          - scenario: tail-sampling
            tier: oss
            language: python
          - scenario: tail-sampling
            tier: oss
            language: java
          - scenario: tail-sampling
            tier: enterprise
            language: nodejs
          - scenario: tail-sampling
            tier: enterprise
            language: python
          - scenario: tail-sampling
            tier: enterprise
            language: java
          - scenario: head-sampling-http
            tier: oss
            language: nodejs
          - scenario: head-sampling-http
            tier: enterprise
            language: nodejs
          - scenario: head-sampling-grpc
            tier: oss
            language: nodejs
          - scenario: head-sampling-grpc
            tier: enterprise
            language: nodejs
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/odigos-scenario-e2e
        with:
          odigos_version: ${{ inputs.odigos_version }}
          scenario: ${{ matrix.scenario }}
          languages: ${{ matrix.language }}
          tier: ${{ matrix.tier }}
        env:
          ODIGOS_TOKEN_SYNTHTIC_APPS_TESTS_CI: ${{ secrets.ODIGOS_TOKEN_SYNTHTIC_APPS_TESTS_CI }}
          DEPOT_SYNTHTIC_APPS_PULL_TOKEN: ${{ secrets.DEPOT_SYNTHTIC_APPS_PULL_TOKEN }}
