name: Release Synthetic Apps

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: 'write'
  packages: write

jobs:
  publish-docker-images:
    strategy:
      matrix:
        include:
          - deploymenttype: httpserver
          - deploymenttype: versionlatest
          - deploymenttype: versionminimum
          - deploymenttype: versionunsupported
          - deploymenttype: versionveryold
          - deploymenttype: envdockerfile
          - deploymenttype: envmanifest
    runs-on: ubuntu-latest
    steps:
      - name: Store new version in env
        run: echo "TAG=${GITHUB_REF##refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image for ${{ matrix.deploymenttype }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/nodejs-httpserver:${{ matrix.deploymenttype }}
          platforms: linux/amd64,linux/arm64
          file: nodejs/httpserver/deployments/${{ matrix.deploymenttype }}/Dockerfile
          context: nodejs/httpserver 