name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
    version-test:
      runs-on: ubuntu-latest
      steps:

        - name: Checkout code
          uses: actions/checkout@v4
      
        - name: Create Kind Cluster
          uses: helm/kind-action@v1.12.0
          with:
            node_image: ${{ matrix.kind-image }}
            version: 'v0.25.0'
            cluster_name: kind
        
        - name: Install chainsaw
          uses: kyverno/action-install-chainsaw@v0.2.12
    
        - name: Run E2E Tests
          run: |
            chainsaw test tests/runtime-version          
                